export const ShopCategories = [
  {
    id: 'mens-fashion',
    label: "Men's Fashion",
    slug: 'mens-fashion',
    description: 'Clothing, footwear, and accessories for men.',
    icon: 'shirt',
  },
  {
    id: 'womens-fashion',
    label: "Women's Fashion",
    slug: 'womens-fashion',
    description: 'Fashion apparel, shoes, and accessories for women.',
    icon: 'sparkles',
  },
  {
    id: 'kids-and-baby',
    label: 'Kids & Baby',
    slug: 'kids-and-baby',
    description: 'Clothing, accessories, and essentials for kids and babies.',
    icon: 'baby',
  },
  {
    id: 'footwear',
    label: 'Footwear',
    slug: 'footwear',
    description: 'Shoes, sneakers, sandals, boots, and slippers.',
    icon: 'footprints',
  },
  {
    id: 'bags-and-luggage',
    label: 'Bags & Luggage',
    slug: 'bags-and-luggage',
    description: 'Handbags, backpacks, wallets, and travel luggage.',
    icon: 'briefcase',
  },
  {
    id: 'jewelry-and-accessories',
    label: 'Jewelry & Accessories',
    slug: 'jewelry-and-accessories',
    description: 'Jewelry, sunglasses, belts, and fashion accessories.',
    icon: 'gem',
  },
  {
    id: 'watches',
    label: 'Watches',
    slug: 'watches',
    description: 'Analog, digital, and smart watches.',
    icon: 'watch',
  },
  {
    id: 'beauty-and-personal-care',
    label: 'Beauty & Personal Care',
    slug: 'beauty-and-personal-care',
    description: 'Skincare, cosmetics, fragrances, and personal care products.',
    icon: 'heart',
  },
  {
    id: 'sportswear-and-activewear',
    label: 'Sportswear & Activewear',
    slug: 'sportswear-and-activewear',
    description: 'Gym wear, activewear, and sports accessories.',
    icon: 'dumbbell',
  },
  {
    id: 'ethnic-and-traditional-wear',
    label: 'Ethnic & Traditional Wear',
    slug: 'ethnic-and-traditional-wear',
    description: 'Traditional and cultural clothing from various regions.',
    icon: 'crown',
  },
  {
    id: 'luxury-and-designer',
    label: 'Luxury & Designer',
    slug: 'luxury-and-designer',
    description: 'Premium and designer fashion brands and products.',
    icon: 'diamond',
  },
  {
    id: 'thrift-and-vintage',
    label: 'Thrift & Vintage',
    slug: 'thrift-and-vintage',
    description: 'Pre-owned, vintage, and sustainable fashion items.',
    icon: 'recycle',
  },
  {
    id: 'custom-and-handmade',
    label: 'Custom & Handmade',
    slug: 'custom-and-handmade',
    description: 'Handcrafted and made-to-order fashion products.',
    icon: 'hammer',
  },
]

export type ShopCategory = (typeof ShopCategories)[number]
