/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  shops: {
    auth: {
      ShopRegistrations: () => import('#controllers/shops/auth/shop_registrations_controller'),
    },
    dashboard: {
      ShopDashboard: () => import('#controllers/shops/dashboard/shop_dashboard_controller'),
      ShopSettings: () => import('#controllers/shops/dashboard/shop_settings_controller'),
    },
  },
}
