/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AttributeValueSchema extends BaseModel {
  static $columns = ['attributeId', 'createdAt', 'id', 'slug', 'updatedAt', 'value'] as const
  $columns = AttributeValueSchema.$columns
  @column()
  declare attributeId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class AttributeSchema extends BaseModel {
  static $columns = ['createdAt', 'filterable', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = AttributeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filterable: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartItemSchema extends BaseModel {
  static $columns = ['cartId', 'createdAt', 'id', 'productVariantId', 'quantity', 'updatedAt'] as const
  $columns = CartItemSchema.$columns
  @column()
  declare cartId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productVariantId: string
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CartSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'sessionId', 'updatedAt', 'userId'] as const
  $columns = CartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sessionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'image', 'isActive', 'name', 'parentId', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare parentId: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GlobalRolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'globalRoleId', 'permissionId', 'updatedAt'] as const
  $columns = GlobalRolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare globalRoleId: string
  @column()
  declare permissionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GlobalRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = GlobalRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GlobalUserRoleSchema extends BaseModel {
  static $columns = ['globalRoleId', 'userId'] as const
  $columns = GlobalUserRoleSchema.$columns
  @column()
  declare globalRoleId: string
  @column()
  declare userId: string
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'productId', 'productNameSnapshot', 'productVariantId', 'productVariantSnapshot', 'quantity', 'shopId', 'skuSnapshot', 'subTotal', 'unitPrice'] as const
  $columns = OrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column()
  declare productId: string
  @column()
  declare productNameSnapshot: string
  @column()
  declare productVariantId: string | null
  @column()
  declare productVariantSnapshot: string | null
  @column()
  declare quantity: number
  @column()
  declare shopId: string
  @column()
  declare skuSnapshot: string | null
  @column()
  declare subTotal: string
  @column()
  declare unitPrice: string
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'discountTotal', 'grandTotal', 'id', 'notes', 'orderNumber', 'paymentStatus', 'placedAt', 'shippingTotal', 'status', 'subtotal', 'updatedAt', 'userAddressId', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discountTotal: string
  @column()
  declare grandTotal: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column()
  declare orderNumber: string
  @column()
  declare paymentStatus: string
  @column.dateTime()
  declare placedAt: DateTime | null
  @column()
  declare shippingTotal: string
  @column()
  declare status: string
  @column()
  declare subtotal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAddressId: string | null
  @column()
  declare userId: string
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'gatewayResponse', 'id', 'orderId', 'paidAt', 'provider', 'status', 'transactionReference', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gatewayResponse: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare provider: string
  @column()
  declare status: string
  @column()
  declare transactionReference: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductMediaSchema extends BaseModel {
  static $columns = ['altText', 'createdAt', 'id', 'metadata', 'productId', 'provider', 'sortOrder', 'thumbnailUrl', 'type', 'url', 'variantId'] as const
  $columns = ProductMediaSchema.$columns
  @column()
  declare altText: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare metadata: any | null
  @column()
  declare productId: string
  @column()
  declare provider: string | null
  @column()
  declare sortOrder: string | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare type: string
  @column()
  declare url: string
  @column()
  declare variantId: string | null
}

export class ProductVariantAttributeValueSchema extends BaseModel {
  static $columns = ['attributeValueId', 'productVariantId'] as const
  $columns = ProductVariantAttributeValueSchema.$columns
  @column()
  declare attributeValueId: string
  @column()
  declare productVariantId: string
}

export class ProductVariantSchema extends BaseModel {
  static $columns = ['comparePrice', 'createdAt', 'id', 'price', 'productId', 'quantity', 'sku', 'status', 'updatedAt', 'weight'] as const
  $columns = ProductVariantSchema.$columns
  @column()
  declare comparePrice: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare price: string
  @column()
  declare productId: string
  @column()
  declare quantity: number
  @column()
  declare sku: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: string | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['brand', 'categoryId', 'createdAt', 'deletedAt', 'description', 'id', 'isFeatured', 'name', 'publishedAt', 'shopId', 'slug', 'status', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare brand: string | null
  @column()
  declare categoryId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isFeatured: boolean
  @column()
  declare name: string
  @column()
  declare publishedAt: string | null
  @column()
  declare shopId: string
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShopRolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'shopRoleId'] as const
  $columns = ShopRolePermissionSchema.$columns
  @column()
  declare permissionId: string
  @column()
  declare shopRoleId: string
}

export class ShopRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'shopId', 'slug', 'updatedAt'] as const
  $columns = ShopRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare shopId: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShopStaffAssignmentSchema extends BaseModel {
  static $columns = ['joinedAt', 'shopId', 'shopRoleId', 'userId'] as const
  $columns = ShopStaffAssignmentSchema.$columns
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare shopId: string
  @column()
  declare shopRoleId: string
  @column()
  declare userId: string
}

export class ShopSchema extends BaseModel {
  static $columns = ['banner', 'createdAt', 'deletedAt', 'description', 'email', 'id', 'logo', 'name', 'ownerId', 'phone', 'slug', 'status', 'updatedAt', 'verifiedAt'] as const
  $columns = ShopSchema.$columns
  @column()
  declare banner: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare ownerId: string
  @column()
  declare phone: string | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class UserAddressSchema extends BaseModel {
  static $columns = ['area', 'city', 'country', 'createdAt', 'district', 'id', 'isDefault', 'label', 'municipality', 'postalCode', 'province', 'recipientName', 'recipientPhone', 'streetAddress', 'updatedAt', 'userId'] as const
  $columns = UserAddressSchema.$columns
  @column()
  declare area: string | null
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare district: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare label: string | null
  @column()
  declare municipality: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare province: string
  @column()
  declare recipientName: string
  @column()
  declare recipientPhone: string | null
  @column()
  declare streetAddress: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'deletedAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'lastLoginAt', 'password', 'phone', 'status', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
